# 启用此项可在服务器控制台查看详细的插件活动
# 有助于调试问题
debug: false

# 自定义分隔符
delimiter: "@"

# 由方块引起的爆炸 (例如: 床、重生锚) 的设置
block-explosion:
  # 设置为 true 以启用基于方块的爆炸日志记录
  enable: true
  # 如果为 true, 则当插件无法确定爆炸源 (玩家/原因) 时, 它将取消爆炸
  # 这可以防止使用无法追踪的爆炸源进行破坏
  disable-unknown: false
  # 当未知爆炸被阻止时, 发送给附近玩家的消息
  alert: "你附近的一个爆炸被阻止了, 因为它来源不明"

# 由实体引起的爆炸 (例如: TNT、苦力怕、火球、风弹) 的设置
entity-explosion:
  # 设置为 true 以启用基于实体的爆炸日志记录
  enable: true
  # 如果为 true, 则当插件无法确定爆炸源时, 它将取消爆炸
  disable-unknown: false
  # 当未知爆炸被阻止时, 发送给附近玩家的消息
  alert: "你附近的一个爆炸被阻止了, 因为它来源不明"

# 火焰蔓延日志记录的设置
fire:
  # 设置为 true 以启用被火烧毁方块的日志记录
  enable: true
  # 如果为 true, 则当插件无法确定火焰的原始来源时, 它将阻止火焰蔓延
  disable-unknown: false
  # 当火焰蔓延被阻止时, 发送给附近玩家的消息
  alert: "火焰蔓延被阻止了, 因为它来源不明"
